// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://samzpmihcgmjccakzuxl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNhbXpwbWloY2dtamNjYWt6dXhsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTczOTI3MjQsImV4cCI6MjA3Mjk2ODcyNH0.XI9QuL0Q2xXnarvcK2HhVFN_d17MRJIVHWxmZNyDSxk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});